{% set name = "secml" %}
{% set version = "0.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/secml-{{ version }}.zip
  sha256: 5aafb1ef5fa80ecb60d72f588e582442d59aa966cc22b98f1c092d04297898fd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib >=0.14
    - matplotlib-base >=3
    - numpy >=1.17
    - pillow >=6.2.1
    - python >={{ python_min }},<3.9
    - python-dateutil
    - requests
    - scikit-learn >=0.22
    - scipy >=1.3.2

test:
  imports:
    - secml
    - secml.adv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://secml.gitlab.io
  summary: A library for Secure and Explainable Machine Learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Walter-0
    - mxr-conda
